cd "C:\Users\Francesco\Documents\GitHub\Win-Python-Backdoor\svc1user_msi"
"C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" "svc1user_win32.wxs"
"C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -sw -out "svc1user_win32.msi" "svc1user_win32.wixobj"
del "svc1user_win32.wixobj"
del "svc1user_win32.wixpdb"
"C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -sw "svc1user_win64.wxs"
"C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" -sw -out "svc1user_win64.msi" "svc1user_win64.wixobj"
del "svc1user_win64.wixobj"
del "svc1user_win64.wixpdb"
pause
